# Generated by Django 5.2.17 on 2026-09-21 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('queued', 'En cola'), ('printing', 'Imprimiendo'), ('finishing', 'Postprocesado'), ('ready', 'Listo'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='confirmed', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'pedido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_estimate', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('configuration', models.JSONField(default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
