# Generated by Django 5.2.17 on 2026-09-21 12:31

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bijutsu Printing', max_length=100, verbose_name='nombre')),
                ('logo', models.ImageField(blank=True, upload_to=apps.core.files.image_path)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('instagram', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
    ]
