# Generated by Django 5.2.17 on 2026-09-21 12:31

import apps.core.files
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('image', models.ImageField(blank=True, upload_to=apps.core.files.image_path, verbose_name='imagen')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='thumbnails/')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['order', 'name'],
            },
            bases=(apps.core.files.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=255, verbose_name='descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('technology', models.CharField(choices=[('fdm', 'Filamento / FDM'), ('resin', 'Resina')], max_length=10, verbose_name='tecnología')),
                ('kind', models.CharField(choices=[('standard', 'Producto FDM / resina'), ('kit', 'Model Kit')], default='standard', max_length=15, verbose_name='tipo')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio base CLP')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_new', models.BooleanField(default=False, verbose_name='nuevo')),
                ('is_demo', models.BooleanField(default=False, verbose_name='dato demo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('image', models.ImageField(blank=True, upload_to=apps.core.files.image_path, verbose_name='imagen principal')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='thumbnails/')),
                ('lead_time', models.CharField(blank=True, max_length=100, verbose_name='tiempo de fabricación')),
                ('internal_notes', models.TextField(blank=True, verbose_name='observaciones internas')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='código interno')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'ordering': ['order', 'name'],
            },
            bases=(apps.core.files.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.files.image_path, verbose_name='imagen')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='thumbnails/')),
                ('alt', models.CharField(max_length=160, verbose_name='texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_primary', models.BooleanField(default=False, verbose_name='principal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
            bases=(apps.core.files.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('required', models.BooleanField(default=True, verbose_name='obligatoria')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.product')),
            ],
            options={
                'verbose_name': 'opción de producto',
                'verbose_name_plural': 'opciones de producto',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='valor')),
                ('surcharge', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='recargo CLP')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.productoption')),
            ],
            options={
                'verbose_name': 'valor de opción',
                'verbose_name_plural': 'valores de opciones',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='propiedad (escala, altura, piezas...)')),
                ('value', models.CharField(max_length=160, verbose_name='valor')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='product_nonnegative_price'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='one_primary_image'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.CheckConstraint(condition=models.Q(('surcharge__gte', 0)), name='option_nonnegative_surcharge'),
        ),
    ]
