# Generated by Django 5.2.17 on 2026-09-21 12:31

import apps.core.files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('technology', models.CharField(choices=[('fdm', 'Filamento / FDM'), ('resin', 'Resina')], max_length=10, verbose_name='tecnología')),
                ('image', models.ImageField(upload_to=apps.core.files.image_path, verbose_name='fotografía')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='thumbnails/')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('active', models.BooleanField(default=True, verbose_name='visible')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
            options={
                'verbose_name': 'trabajo realizado',
                'verbose_name_plural': 'trabajos realizados',
                'ordering': ['order', '-pk'],
            },
            bases=(apps.core.files.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.files.image_path)),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='thumbnails/')),
                ('alt', models.CharField(max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioitem')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
            bases=(apps.core.files.OptimizedImageMixin, models.Model),
        ),
    ]
