# Generated by Django 5.2.17 on 2026-09-21 13:13

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.core.files.image_path, verbose_name='fotografía'),
        ),
    ]
